### ISSUE TITLE
_embed is not working on any request

### ISSUE THREAD

**Issue by gnugomez** [La-Pometa/pometa-wp-headless-api-extension#4]
**Describe the bug**
When you use _embed = true param to get embedded data without additional queries.

**To Reproduce**
1. Go to 'paw/postman' with this plugin enabled
2. Make a post to any endpoint with _embed param
3. Check if you can see _embedded in the response data

**Expected behavior**
The response with the embedded data

**Comment by SuportPometa** [comment]
path module update

Commit: https://github.com/La-Pometa/pometa-wp-headless-api-extension/commit/09fb2601bf25367576785b4fcd7863cc92ba1cd2

**Comment by SuportPometa** [comment]
archive module updated

Commit: https://github.com/La-Pometa/pometa-wp-headless-api-extension/commit/994cae874739d0b536781cc1f1174d835d5d3c10

**Comment by SuportPometa** [comment]
Queries with ID (post/<id>, page/<id>, ...) were not affected
